const fs = require('fs');
const path = require('path');
const { zodToTs, createTypeAlias, printNode } = require('zod-to-ts');
const ts = require('typescript');

async function main() {
    const projectRoot = process.cwd();
    const distTypesPath = path.join(projectRoot, 'dist/esm/types.js');
    if (!fs.existsSync(distTypesPath)) {
        console.error('dist/esm/types.js not found. Run `npm run build:esm` first.');
        process.exit(2);
    }

    // dynamic import of ESM bundle
    const typesModule = await import('file://' + distTypesPath);

    // read src/types.ts to collect aliases
    const src = fs.readFileSync(path.join(projectRoot, 'src/types.ts'), 'utf8');
    const typeAliasRe = /export type (\w+) = Infer<typeof (\w+)>;/g;
    let match;
    const aliases = [];
    while ((match = typeAliasRe.exec(src))) {
        aliases.push({ typeName: match[1], schemaName: match[2] });
    }

    if (aliases.length === 0) {
        console.error('no aliases found in src/types.ts');
        process.exit(1);
    }

// helpers to print TS nodes
function nodeToString(node) {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
    const resultFile = ts.createSourceFile('tmp.ts', '', ts.ScriptTarget.Latest);
    return printer.printNode(ts.EmitHint.Unspecified, node, resultFile);
}

// expose these helpers for testing
exports.nodeToString = nodeToString;

function generateForSchema(schema, identifier) {
    // ask zod-to-ts to resolve native enums so we get enum AST nodes in the store
    const result = zodToTs(schema, identifier, { nativeEnums: 'resolve' });
    const node = result.node;
    const typeAlias = createTypeAlias(node, identifier);
    let extra = '';
    // if zod-to-ts returned a store with nodes (enums, etc), print them first
    if (result.store && typeof result.store === 'object') {
        for (const key of Object.keys(result.store)) {
            const val = result.store[key];
            // store entries can be arrays or single nodes
            if (Array.isArray(val)) {
                for (const n of val) {
                    try {
                        extra += printNode(n) + '\n\n';
                    } catch (e) {}
                }
            } else if (val) {
                try {
                    extra += printNode(val) + '\n\n';
                } catch (e) {}
            }
        }
    }
    return { alias: nodeToString(typeAlias), extra };
}

// expose for testing
exports.generateForSchema = generateForSchema;

    const outEsmDir = path.join(projectRoot, 'dist/esm');
    const outCjsDir = path.join(projectRoot, 'dist/cjs');
    fs.mkdirSync(outEsmDir, { recursive: true });
    fs.mkdirSync(outCjsDir, { recursive: true });

    const header = `// Generated by scripts/generate-types.cjs - do not edit\n/* eslint-disable */\n`;
    let out = header + '\n';

    const childProcess = require('child_process');

    function runWorker(filePath) {
        return new Promise((resolve) => {
            const worker = childProcess.spawn(process.execPath, [path.join(__dirname, 'generate-types-worker.cjs'), filePath], { stdio: ['ignore', 'pipe', 'pipe'] });
            let stdout = '';
            let stderr = '';
            worker.stdout.on('data', (c) => stdout += String(c));
            worker.stderr.on('data', (c) => stderr += String(c));
            worker.on('close', () => {
                if (stdout) {
                    try {
                        const obj = JSON.parse(stdout);
                        resolve({ ok: true, data: obj });
                        return;
                    } catch (e) {}
                }
                resolve({ ok: false, error: stderr || stdout });
            });
        });
    }

    // Walk each dist root and generate per-module .d.ts files for modules that export Zod-like schemas
    function walkDir(dir, cb) {
        for (const name of fs.readdirSync(dir)) {
            const full = path.join(dir, name);
            const st = fs.statSync(full);
            if (st.isDirectory()) walkDir(full, cb);
            else cb(full);
        }
    }

    const processed = [];
    const distRoots = [outEsmDir, outCjsDir];

    // collect a global store of extra printed nodes to dedupe across modules
    const globalExtras = new Map();

    for (const root of distRoots) {
        if (!fs.existsSync(root)) continue;
        const jobs = [];
        walkDir(root, (filePath) => {
            if (!filePath.endsWith('.js')) return;
            if (/[/\\]examples[/\\]/.test(filePath)) return;
            if (/[/\\]cli/.test(filePath)) return;
            if (/[/\\]examples-.*/.test(filePath)) return;
            jobs.push(filePath);
        });

        for (const filePath of jobs) {
            const res = await runWorker(filePath);
            if (!res.ok) continue;
            const parsed = res.data;
            if (!parsed || !parsed.success) continue;
            const results = parsed.results || [];
            if (results.length === 0) continue;

            let moduleOut = header + '\n';
            for (const r of results) {
                if (r.error) continue;
                // dedupe extra nodes globally by text
                if (r.extra) {
                    const key = r.extra.trim();
                    if (!globalExtras.has(key)) globalExtras.set(key, r.extra);
                }
                if (r.alias) moduleOut += (r.extra ? r.extra + '\n' : '') + `export ${r.alias}\n\n`;
            }
            const dtsPath = filePath.replace(/\.js$/, '.d.ts');
            try { fs.writeFileSync(dtsPath, moduleOut, 'utf8'); processed.push(dtsPath); } catch (e) {}
        }
    }

    // create consolidated out by collecting unique exported declarations (dedupe by name)
    out = header + '\n';
    const declMap = new Map();

    function collectDeclsFromText(text) {
        if (!text) return;
        // split where 'export ' starts at line boundary
        const parts = text.split(/\n(?=export\s)/g);
        for (const part of parts) {
            const trimmed = part.trim();
            if (!trimmed) continue;
            // try to capture exported declaration name
            const m = trimmed.match(/^export\s+(?:type|interface|enum|declare\s+type)\s+([A-Za-z0-9_]+)/);
            let key = null;
            if (m && m[1]) key = m[1];
            else {
                // fallback: hash the text
                key = 'H_' + String(trimmed).slice(0, 200);
            }
            if (!declMap.has(key)) declMap.set(key, trimmed);
        }
    }

    // collect from extras first (these are likely enums or helper types)
    for (const extra of globalExtras.values()) collectDeclsFromText(extra);

    // collect from per-module outputs
    for (const p of processed) {
        try {
            const txt = fs.readFileSync(p, 'utf8');
            const body = txt.replace(header, '').trim();
            collectDeclsFromText(body);
        } catch (e) {}
    }

    for (const decl of declMap.values()) out += decl + '\n\n';

    // also write a consolidated generated-types file for convenience
    fs.writeFileSync(path.join(outEsmDir, 'generated-types.d.ts'), out, 'utf8');
    fs.writeFileSync(path.join(outCjsDir, 'generated-types.d.ts'), out, 'utf8');

    // Try to overwrite top-level types.d.ts with consolidated output (best-effort)
    try {
        fs.writeFileSync(path.join(outEsmDir, 'types.d.ts'), out, 'utf8');
        fs.writeFileSync(path.join(outCjsDir, 'types.d.ts'), out, 'utf8');
    } catch (e) {}

    console.log('generated per-module d.ts for', processed.length, 'modules');
}

if (require.main === module) {
    main().catch((err) => {
        console.error('generate-types failed', err && err.stack || err);
        process.exit(1);
    });
} else {
    // when required as a module for tests, export helpers
    module.exports = { generateForSchema: exports.generateForSchema, nodeToString: exports.nodeToString };
}
