#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import ts from 'typescript';
import { zodToTs, createTypeAlias, printNode } from 'zod-to-ts';
// Import the zod schemas directly from source
import * as Schemas from '../src/types.ts';

// List of exported schema names to convert into plain TS types.
const schemaNames = [
    // core types
    'ProgressTokenSchema',
    'CursorSchema',
    'RequestSchema',
    'NotificationSchema',
    'ResultSchema',
    'RequestIdSchema',
    'JSONRPCRequestSchema',
    'JSONRPCNotificationSchema',
    'JSONRPCResponseSchema',
    'JSONRPCErrorSchema',
    'JSONRPCMessageSchema',
    // high level exported types mapped in src/types.ts
    // we will prefer to emit the `export type X = ...` for each alias defined in src/types.ts
];

// Also collect the exported type aliases from the compiled source file by scanning the source for lines like `export type Foo = Infer<typeof FooSchema>;`
const src = fs.readFileSync(path.resolve(process.cwd(), 'src/types.ts'), 'utf8');
const typeAliasRe = /export type (\w+) = Infer<typeof (\w+)>;/g;
let match: RegExpExecArray | null;
const aliases: Array<{ typeName: string; schemaName: string }> = [];
while ((match = typeAliasRe.exec(src))) {
    aliases.push({ typeName: match[1], schemaName: match[2] });
}

// Ensure output directories exist
const outEsmDir = path.resolve(process.cwd(), 'dist/esm');
const outCjsDir = path.resolve(process.cwd(), 'dist/cjs');
fs.mkdirSync(outEsmDir, { recursive: true });
fs.mkdirSync(outCjsDir, { recursive: true });

function nodeToString(node: ts.Node) {
    const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
    const resultFile = ts.createSourceFile('tmp.ts', '', ts.ScriptTarget.Latest);
    return printer.printNode(ts.EmitHint.Unspecified, node, resultFile);
}

function generateForSchema(schema: any, identifier: string) {
    const { node } = zodToTs(schema, identifier);
    const typeAlias = createTypeAlias(node, identifier);
    return nodeToString(typeAlias);
}

const header = `// Generated by scripts/generate-types.ts - do not edit
/* eslint-disable */
`;

let out = header + '\n';
for (const a of aliases) {
    const schema = (Schemas as any)[a.schemaName];
    if (!schema) {
        console.warn(`schema not found: ${a.schemaName}`);
        continue;
    }
    try {
        const typeDecl = generateForSchema(schema, a.typeName);
        out += `export ${typeDecl}\n\n`;
    } catch (err) {
        console.error('failed to generate for', a.typeName, err);
    }
}

// write to both dist/esm and dist/cjs
fs.writeFileSync(path.join(outEsmDir, 'generated-types.d.ts'), out, 'utf8');
fs.writeFileSync(path.join(outCjsDir, 'generated-types.d.ts'), out, 'utf8');

console.log('generated types for', aliases.length, 'aliases');
