/*
  scripts/generate-types.ts

  Human-readable TypeScript copy of the post-build generator.

  Purpose
  -------
  - Walk compiled outputs under `dist/esm` and `dist/cjs`.
  - For each compiled module, spawn a worker that requires the compiled module
    at runtime and extracts Zod-like runtime schemas using zod-to-ts.
  - Collect small, deduplicated type aliases (the lightweight TypeScript
    declarations produced by zod-to-ts) and write per-module `.d.ts` files.
  - Run a few best-effort passes (AST-based and regex fallbacks) to replace
    compiler-inlined, huge return types with `Promise<TypeAlias>` references.

  High level flow (ASCII diagram)
  -------------------------------
  (1) tsc builds -> dist/esm & dist/cjs
      |
      v
  (2) this generator (generate-types.ts/cjs)
      |-- walk dist/ (skip examples)
      |-- for each .js file => spawn worker
      v
  (3) worker (generate-types-worker.cjs or .ts)
      |-- require(module)
      |-- detect Zod-like exports
      |-- run zod-to-ts to produce alias AST nodes + any extra declarations
      |-- print JSON -> main
      v
  (4) main collects all alias fragments
      |-- writes per-module .d.ts (with triple-slash ref to generated-types.d.ts)
      |-- writes consolidated generated-types.d.ts (deduped)
      |-- performs AST-based replacement of inlined return types

  Notes
  -----
  - The TS version is a readable copy for maintenance and tests. The project
    currently uses the CJS files at runtime to avoid ESM/CJS interop issues when
    requiring compiled `dist` modules in a worker subprocess.
  - The method-discovery heuristics operate on compiled JS and are intentionally
    best-effort: they look for `this.request({ method: 'x/y' }, SchemaName, ...)` and
    try to find a nearby method name. Replacing constructor signatures is
    explicitly guarded against.

*/

import fs from 'fs';
import path from 'path';
import childProcess from 'child_process';
import ts from 'typescript';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const header = `// Generated by scripts/generate-types.cjs - do not edit\n/* eslint-disable */\n`;

function runWorker(filePath: string): Promise<any> {
  return new Promise((resolve) => {
    // Use the existing CJS worker for runtime compatibility (node can run .cjs)
    const workerPath = path.join(__dirname, 'generate-types-worker.cjs');
    const worker = childProcess.spawn(process.execPath, [workerPath, filePath], { stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';
    worker.stdout.on('data', (c) => (stdout += String(c)));
    worker.stderr.on('data', (c) => (stderr += String(c)));
    worker.on('close', () => {
      if (stdout) {
        try {
          resolve({ ok: true, data: JSON.parse(stdout) });
          return;
        } catch (e) {}
      }
      resolve({ ok: false, error: stderr || stdout });
    });
  });
}

function walkDir(dir: string, cb: (p: string) => void) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) walkDir(full, cb);
    else cb(full);
  }
}

// AST-based replacement: replace method return types with Promise<TypeName>
export function astReplaceReturnTypes(dtsText: string, replacements: Array<{ methodName: string; typeName: string }>) {
  if (!replacements || replacements.length === 0) return { text: dtsText, changed: false };
  const sourceFile = ts.createSourceFile('file.d.ts', dtsText, ts.ScriptTarget.Latest, /*setParentNodes*/ true, ts.ScriptKind.TS);

  const replMap = new Map<string, string>();
  for (const r of replacements) replMap.set(r.methodName, r.typeName);

  function getNameText(nameNode: ts.Node | undefined): string | null {
    if (!nameNode) return null;
    if (ts.isIdentifier(nameNode)) return nameNode.escapedText && String(nameNode.escapedText);
    if (ts.isStringLiteral(nameNode)) return nameNode.text;
    return null;
  }

  let changed = false;

  const transformContextStub = {
    factory: ts.factory,
    getCompilerOptions: () => ({}),
    startLexicalEnvironment: () => {},
    suspendLexicalEnvironment: () => {},
    resumeLexicalEnvironment: () => {},
    endLexicalEnvironment: () => [],
    hoistFunctionDeclaration: () => {},
    hoistVariableDeclaration: () => {},
    requestEmitHelper: () => {},
    readEmitHelpers: () => undefined,
    enableEmitNotification: () => {},
    enableSubstitution: () => {},
    isEmitNotificationEnabled: () => false,
    isSubstitutionEnabled: () => false,
    onEmitNode: () => {},
    onSubstituteNode: () => (hint: any, node: any) => node,
  } as any;

  function visitor(node: ts.Node): ts.Node {
    if (ts.isMethodDeclaration(node) || ts.isMethodSignature(node)) {
      const name = getNameText((node as any).name);
      if (name && replMap.has(name)) {
        const typeName = replMap.get(name)!;
        const newType = ts.factory.createTypeReferenceNode('Promise', [ts.factory.createTypeReferenceNode(typeName, [])]);
        changed = true;
        if (ts.isMethodDeclaration(node)) {
          return ts.factory.updateMethodDeclaration(
            node,
            node.modifiers,
            node.asteriskToken,
            node.name,
            node.questionToken,
            node.typeParameters,
            node.parameters,
            newType,
            node.body
          );
        }
        return ts.factory.updateMethodSignature(node, node.modifiers, node.name, node.questionToken, node.typeParameters, node.parameters, newType);
      }
    }
    return ts.visitEachChild(node, visitor, transformContextStub);
  }

  const transformed = ts.visitNode(sourceFile, visitor) as ts.SourceFile;
  if (!changed) return { text: dtsText, changed: false };
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const newText = printer.printFile(transformed);
  return { text: newText, changed: true };
}

async function main() {
  const projectRoot = process.cwd();
  const outEsmDir = path.join(projectRoot, 'dist/esm');
  const outCjsDir = path.join(projectRoot, 'dist/cjs');
  if (!fs.existsSync(outEsmDir) || !fs.existsSync(outCjsDir)) {
    console.error('dist directories not found. Run build first.');
    process.exit(2);
  }

  const distRoots = [outEsmDir, outCjsDir];
  const processed: string[] = [];
  const globalExtras = new Map<string, string>();
  const globalSchemaMap = new Map<string, string>();

  // collect per-file source exports early so we can inject them into per-module outputs
  // declared here to ensure it's available during module processing below
  let perFileSourceDecls = new Map<string, string[]>();
  try {
    collectSourceExports(path.join(process.cwd(), 'src'));
    perFileSourceDecls = collectSourceExportsPerFile(path.join(process.cwd(), 'src'));
  } catch (e) {}

  // probe central types modules to build export -> typeName map and collect extras
  for (const typesFile of [path.join(outEsmDir, 'types.js'), path.join(outCjsDir, 'types.js')]) {
    try {
      if (!fs.existsSync(typesFile)) continue;
      const tr = await runWorker(typesFile);
      if (!tr.ok || !tr.data || !tr.data.success) continue;
      for (const r of tr.data.results || []) {
        if (r && r.exportName && r.typeName) globalSchemaMap.set(r.exportName, r.typeName);
        if (r && r.extra) {
          const key = r.extra.trim();
          if (!globalExtras.has(key)) globalExtras.set(key, r.extra);
        }
      }
    } catch (e) {}
  }

  for (const root of distRoots) {
    if (!fs.existsSync(root)) continue;
    const jobs: string[] = [];
    walkDir(root, (filePath) => {
      if (!filePath.endsWith('.js')) return;
      if (/[/\\]examples([/\\]|$)/.test(filePath)) return; // only skip examples
      jobs.push(filePath);
    });

    // prepare a mapping by probing the root's types.js if present
    const schemaExportToTypeName = new Map(globalSchemaMap);
    try {
      const typesJs = path.join(root, 'types.js');
      if (fs.existsSync(typesJs)) {
        const tr = await runWorker(typesJs);
        if (tr.ok && tr.data && tr.data.success) {
          for (const r of tr.data.results || []) if (r && r.exportName && r.typeName) schemaExportToTypeName.set(r.exportName, r.typeName);
          for (const r of tr.data.results || []) if (r && r.extra) {
            const k = r.extra.trim();
            if (!globalExtras.has(k)) globalExtras.set(k, r.extra);
          }
        }
      }
    } catch (e) {}

    for (const filePath of jobs) {
      let jsSrc = '';
      try {
        jsSrc = fs.readFileSync(filePath, 'utf8');
      } catch (e) {
        jsSrc = '';
      }

      // try to update existing d.ts via AST replacements
      try {
        const requestRe = /this\.request\(\s*\{([\s\S]*?)\}\s*,\s*([A-Za-z0-9_]+)\s*,/g;
        const setHandlerRe = /setRequestHandler\(\s*([A-Za-z0-9_]+)\s*,/g;
        let m: RegExpExecArray | null;
        const dtsPath = filePath.replace(/\.js$/, '.d.ts');
        if (fs.existsSync(dtsPath)) {
          let dtsText = fs.readFileSync(dtsPath, 'utf8');
          const replacements: Array<{ methodName: string; typeName: string }> = [];
          // find request() usages
          while ((m = requestRe.exec(jsSrc))) {
            const objText = m[1];
            const schemaName = m[2];
            const methodMatch = objText.match(/method\s*:\s*['\"]([^'\"]+)['\"]/);
            if (!methodMatch) continue;
            const protoMethod = methodMatch[1];
            const typeName = schemaExportToTypeName.get(schemaName);
            if (!typeName) continue;
            const methodFinder = new RegExp('(?:async\\s+)?([A-Za-z0-9_]+)\\s*\\([^\\)]*\\)\\s*\\{[\\s\\S]*?this\\.request\\(\\s*\\{[\\s\\S]*?method\\s*:\\s*["\']' + protoMethod.replace(/[.*+?^${}()|[\\\\]\\]/g,'\\$&') + '["\"][\\s\\S]*?\\)', 'm');
            const mf = jsSrc.match(methodFinder);
            let methodName: string | null = null;
            if (mf && mf[1]) methodName = mf[1];
            if (!methodName) methodName = protoMethod.split('/').pop() || null;
            if (methodName && methodName !== 'constructor') replacements.push({ methodName, typeName });
          }
          // find setRequestHandler usages: try to map schema -> method via request schema's .shape.method.value when possible
          try {
            let sm: RegExpExecArray | null;
            while ((sm = setHandlerRe.exec(jsSrc))) {
              const schemaIdent = sm[1];
              const typeName = schemaExportToTypeName.get(schemaIdent);
              if (!typeName) continue;
              const shapeRe = new RegExp(schemaIdent + '\\.[a-zA-Z0-9_\\.\'" ]*method', 'g');
              const methodLiteralFinder = new RegExp(schemaIdent + '[^\n]{0,200}method\s*:\s*["\']([^"\']+)["\']', 'g');
              const mf = methodLiteralFinder.exec(jsSrc);
              let protoMethod: string | null = null;
              if (mf && mf[1]) protoMethod = mf[1];
              if (!protoMethod) {
                const handlerBlockFinder = new RegExp('setRequestHandler\\([^,]+,([\\s\\S]{0,200})\\)', 'g');
                const hb = handlerBlockFinder.exec(jsSrc);
                if (hb && hb[1]) {
                  const lit = hb[1].match(/method\s*:\s*["']([^"']+)["']/);
                  if (lit && lit[1]) protoMethod = lit[1];
                }
              }
              let methodName: string | null = null;
              if (protoMethod) methodName = protoMethod.split('/').pop() || null;
              if (methodName && methodName !== 'constructor') replacements.push({ methodName, typeName });
            }
          } catch (e) {}
          if (replacements.length > 0) {
            try {
              const astRes = astReplaceReturnTypes(dtsText, replacements);
              if (astRes.changed) {
                dtsText = astRes.text;
                try {
                  const genPath = path.join(root, 'generated-types.d.ts');
                  const rel = path.relative(path.dirname(dtsPath), genPath).replace(/\\/g, '/');
                  const ref = '/// <reference path="' + rel + '" />\n';
                  if (!dtsText.startsWith(ref)) dtsText = ref + dtsText;
                } catch (e) {}

                // Inject per-file source declarations if we can map the JS -> source
                try {
                  // compute candidate source path relative to project
                  const candidate = filePath.replace(/\.js$/, '.ts');
                  const relCandidate = path.relative(path.join(process.cwd(), 'dist'), candidate).replace(/\\/g, '/');
                  // candidate may be like 'esm/shared/auth.ts' or 'cjs/shared/auth.ts'; try both
                  const possibleSrc = [path.join('src', relCandidate.replace(/^esm\//, '').replace(/^cjs\//, '')), path.join('src', relCandidate)];
                  for (const p of possibleSrc) {
                    const normalized = path.normalize(p).replace(/\\/g, '/');
                    if (perFileSourceDecls && perFileSourceDecls.has(normalized)) {
                      const decls = perFileSourceDecls.get(normalized)!;
                      for (const d of decls) {
                        if (!dtsText.includes(d)) dtsText += '\n\n' + d;
                      }
                      break;
                    }
                  }
                } catch (e) {}
                fs.writeFileSync(dtsPath, dtsText, 'utf8');
                processed.push(dtsPath);
              }
            } catch (e) {}
          }
        }
      } catch (e) {}

      // run worker to extract aliases/extras for this module
      try {
        const res = await runWorker(filePath);
        if (!res.ok) continue;
        const parsed = res.data;
        if (!parsed || !parsed.success) continue;
        const results = parsed.results || [];
        if (results.length === 0) continue;

        let moduleOut = header + '\n';
        for (const r of results) {
          if (r.error) continue;
          if (r.extra) {
            const key = r.extra.trim();
            if (!globalExtras.has(key)) globalExtras.set(key, r.extra);
          }
          if (r.alias) moduleOut += (r.extra ? r.extra + '\n' : '') + `export ${r.alias}\n\n`;
          // Emit lightweight value declarations for runtime schema exports so `typeof XSchema` is valid in d.ts
          if (r.exportName && /Schema$/.test(r.exportName)) {
            moduleOut += `export declare const ${r.exportName}: any;\n\n`;
          }
        }

        // Preserve any existing non-zod exported type/interface/declare blocks from the original
        // .d.ts produced by tsc for this module. Some types (like union aliases) are handwritten
        // in source and won't be produced by zod-to-ts; copy them across to avoid accidentally
        // dropping them when regenerating.
        try {
          const existingDtsPath = filePath.replace(/\.js$/, '.d.ts');
          if (fs.existsSync(existingDtsPath)) {
            const existingText = fs.readFileSync(existingDtsPath, 'utf8');
            // Find exported type/interface/declare type blocks up to the next blank line or semicolon.
            const declRe = /(^export\s+(?:type|interface|declare\s+type|declare\s+interface)\s+[A-Za-z0-9_][\s\S]*?;)(?:\s*\n|\n\s*\n)/gm;
            let m2: RegExpExecArray | null;
            while ((m2 = declRe.exec(existingText))) {
              const declBlock = m2[1].trim();
              // avoid duplicating declarations already added by zod-to-ts
              if (!moduleOut.includes(declBlock)) {
                moduleOut += declBlock + '\n\n';
              }
            }
          }
        } catch (e) {}

        // apply module-level replacements so per-module aliases are used
        try {
          const requestRe = /this\.request\(\s*\{([\s\S]*?)\}\s*,\s*([A-Za-z0-9_]+)\s*,/g;
          const setHandlerRe = /setRequestHandler\(\s*([A-Za-z0-9_]+)\s*,/g;
          let m: RegExpExecArray | null;
          const moduleReplacements: Array<{ methodName: string; typeName: string }> = [];
          while ((m = requestRe.exec(jsSrc))) {
            const objText = m[1];
            const schemaName = m[2];
            const methodMatch = objText.match(/method\s*:\s*['\"]([^'\"]+)['\"]/);
            if (!methodMatch) continue;
            const protoMethod = methodMatch[1];
            const finalTypeName = schemaExportToTypeName.get(schemaName);
            if (!finalTypeName) continue;
            const methodFinder = new RegExp('(?:async\\s+)?([A-Za-z0-9_]+)\\s*\\([^\\)]*\\)\\s*\\{[\\s\\S]*?this\\.request\\(\\s*\\{[\\s\\S]*?method\\s*:\\s*["\']' + protoMethod.replace(/[.*+?^${}()|[\\\\]\\]/g,'\\$&') + '["\"][\\s\\S]*?\\)', 'm');
            const mf = jsSrc.match(methodFinder);
            let methodName: string | null = null;
            if (mf && mf[1]) methodName = mf[1];
            if (!methodName) methodName = protoMethod.split('/').pop() || null;
            if (methodName && methodName !== 'constructor') moduleReplacements.push({ methodName, typeName: finalTypeName });
          }
          try {
            let sm: RegExpExecArray | null;
            while ((sm = setHandlerRe.exec(jsSrc))) {
              const schemaIdent = sm[1];
              const finalTypeName = schemaExportToTypeName.get(schemaIdent);
              if (!finalTypeName) continue;
              const methodLiteralFinder = new RegExp(schemaIdent + '[^\n]{0,200}method\s*:\s*["\']([^"\']+)["\']', 'g');
              const mf = methodLiteralFinder.exec(jsSrc);
              let protoMethod: string | null = null;
              if (mf && mf[1]) protoMethod = mf[1];
              let methodName: string | null = null;
              if (protoMethod) methodName = protoMethod.split('/').pop() || protoMethod;
              if (methodName && methodName !== 'constructor') moduleReplacements.push({ methodName, typeName: finalTypeName });
            }
          } catch (e) {}
          if (moduleReplacements.length > 0) {
            const astRes = astReplaceReturnTypes(moduleOut, moduleReplacements);
            if (astRes.changed) moduleOut = astRes.text;
          }
        } catch (e) {}

        // write per-module d.ts and a minimal map
        try {
          const dtsPath = filePath.replace(/\.js$/, '.d.ts');
          const mapObj: any = { version: 3, file: path.basename(dtsPath), sources: [], sourcesContent: [], names: [], mappings: '' };
          const jsMapPath = filePath + '.map';
          if (fs.existsSync(jsMapPath)) {
            try {
              const jm = JSON.parse(fs.readFileSync(jsMapPath, 'utf8'));
              if (Array.isArray(jm.sources)) mapObj.sources = jm.sources;
              if (Array.isArray(jm.sourcesContent)) mapObj.sourcesContent = jm.sourcesContent;
            } catch (e) {}
          } else {
            const candidate = filePath.replace(/\.js$/, '.ts');
            if (fs.existsSync(candidate)) {
              mapObj.sources = [path.relative(path.dirname(dtsPath), candidate)];
              try { mapObj.sourcesContent = [fs.readFileSync(candidate, 'utf8')]; } catch (e) { mapObj.sourcesContent = []; }
            }
          }
          try {
            const genPath = path.join(root, 'generated-types.d.ts');
            const rel = path.relative(path.dirname(dtsPath), genPath).replace(/\\/g, '/');
            const ref = '/// <reference path="' + rel + '" />\n';
            if (!moduleOut.startsWith(ref)) moduleOut = ref + moduleOut;
          } catch (e) {}

          fs.writeFileSync(dtsPath, moduleOut + '\n//# sourceMappingURL=' + path.basename(dtsPath) + '.map\n', 'utf8');
          try { fs.writeFileSync(dtsPath + '.map', JSON.stringify(mapObj), 'utf8'); } catch (e) {}
          processed.push(dtsPath);
        } catch (e) {}
      } catch (e) {}
    }
  }

  // assemble consolidated generated-types.d.ts from collected extras and processed module outputs
  let out = header + '\n';
  const declMap = new Map<string, string>();
  function collectDeclsFromText(text?: string) {
    if (!text) return;
    const parts = text.split(/\n(?=export\s)/g);
    for (const part of parts) {
      const trimmed = part.trim();
      if (!trimmed) continue;
      const m = trimmed.match(/^export\s+(?:type|interface|enum|declare\s+type)\s+([A-Za-z0-9_]+)/);
      let key: string | null = null;
      if (m && m[1]) key = m[1];
      else key = 'H_' + String(trimmed).slice(0, 200);
      if (!declMap.has(key)) declMap.set(key, trimmed);
    }
  }

  // Collect exported type/interface/enum declarations straight from source `src/`.
  // This is the robust path to ensure type-only exports (not produced by zod-to-ts)
  // are preserved in generated-types.d.ts even after a clean rebuild.
  function collectSourceExports(srcRoot: string) {
    try {
      const files: string[] = [];
      function walkSrc(dir: string) {
        for (const name of fs.readdirSync(dir)) {
          const full = path.join(dir, name);
          const st = fs.statSync(full);
          if (st.isDirectory()) walkSrc(full);
          else if (full.endsWith('.ts') && !full.endsWith('.d.ts')) files.push(full);
        }
      }
      walkSrc(srcRoot);
      for (const f of files) {
        try {
          const srcText = fs.readFileSync(f, 'utf8');
          const sf = ts.createSourceFile(f, srcText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
          for (const stmt of sf.statements) {
            // exported type/interface/enum declarations
            if ((ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt) || ts.isEnumDeclaration(stmt))) {
              const isExported = stmt.modifiers && stmt.modifiers.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
              if (!isExported) continue;
              const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
              const printed = printer.printNode(ts.EmitHint.Unspecified, stmt, sf);
              // ensure exported keyword present
              const declText = printed.trim().startsWith('export') ? printed : 'export ' + printed;
              const name = (stmt as any).name && (stmt as any).name.escapedText ? String((stmt as any).name.escapedText) : 'H_SRC';
              if (!declMap.has(name)) declMap.set(name, declText.trim());
            }
          }
        } catch (e) {}
      }
    } catch (e) {}
  }

  // Also collect per-source-file exported declarations so we can inject them into
  // the corresponding per-module `.d.ts` outputs (making each module more standalone).
  function collectSourceExportsPerFile(srcRoot: string) {
    const perFile = new Map<string, string[]>();
    try {
      const files: string[] = [];
      function walkSrc(dir: string) {
        for (const name of fs.readdirSync(dir)) {
          const full = path.join(dir, name);
          const st = fs.statSync(full);
          if (st.isDirectory()) walkSrc(full);
          else if (full.endsWith('.ts') && !full.endsWith('.d.ts')) files.push(full);
        }
      }
      walkSrc(srcRoot);
      for (const f of files) {
        try {
          const srcText = fs.readFileSync(f, 'utf8');
          const sf = ts.createSourceFile(f, srcText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
          const arr: string[] = [];
          for (const stmt of sf.statements) {
            if ((ts.isTypeAliasDeclaration(stmt) || ts.isInterfaceDeclaration(stmt) || ts.isEnumDeclaration(stmt))) {
              const isExported = stmt.modifiers && stmt.modifiers.some((m) => m.kind === ts.SyntaxKind.ExportKeyword);
              if (!isExported) continue;
              const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
              const printed = printer.printNode(ts.EmitHint.Unspecified, stmt, sf);
              const declText = printed.trim().startsWith('export') ? printed : 'export ' + printed;
              arr.push(declText.trim());
            }
          }
          if (arr.length > 0) perFile.set(path.relative(process.cwd(), f).replace(/\\/g, '/'), arr);
        } catch (e) {}
      }
    } catch (e) {}
    return perFile;
  }

  for (const extra of globalExtras.values()) collectDeclsFromText(extra);
  // collect source exports from `src` root (project-relative)
  try {
    collectSourceExports(path.join(process.cwd(), 'src'));
    // perFileSourceDecls is declared earlier so it is available during module processing
    // and populated here.
    const _perFile = collectSourceExportsPerFile(path.join(process.cwd(), 'src'));
    for (const [k, v] of _perFile) perFileSourceDecls.set(k, v);
  } catch (e) {}
  for (const p of processed) {
    try {
      const txt = fs.readFileSync(p, 'utf8');
      const body = txt.replace(header, '').trim();
      collectDeclsFromText(body);
    } catch (e) {}
  }
  for (const decl of declMap.values()) out += decl + '\n\n';

  try {
    fs.writeFileSync(path.join(outEsmDir, 'generated-types.d.ts'), out, 'utf8');
    fs.writeFileSync(path.join(outCjsDir, 'generated-types.d.ts'), out, 'utf8');
  } catch (e) {}

  // Post-pass: for each processed .d.ts, examine its corresponding .js to find this.request(..., SchemaName, ...)
  // and replace large inline Promise<...> return types with Promise<TypeName> where available in globalSchemaMap.
  for (const dtsPath of processed.slice()) {
    try {
      const jsPath = dtsPath.replace(/\.d\.ts$/, '.js');
      if (!fs.existsSync(jsPath) || !fs.existsSync(dtsPath)) continue;
      const jsSrc = fs.readFileSync(jsPath, 'utf8');
      let dtsText = fs.readFileSync(dtsPath, 'utf8');
      let changed = false;
      const requestRe = /this\.request\(\s*\{([\s\S]*?)\}\s*,\s*([A-Za-z0-9_]+)\s*,/g;
      let m: RegExpExecArray | null;
      while ((m = requestRe.exec(jsSrc))) {
        const objText = m[1];
        const schemaName = m[2];
        const methodMatch = objText.match(/method\s*:\s*['\"]([^'\"]+)['\"]/);
        if (!methodMatch) continue;
        const protoMethod = methodMatch[1];
        const typeName = globalSchemaMap.get(schemaName);
        if (!typeName) continue;

        const methodFinder = new RegExp('(?:async\\s+)?([A-Za-z0-9_]+)\\s*\\([^\\)]*\\)\\s*\\{[\\s\\S]*?this\\.request\\(\\s*\\{[\\s\\S]*?method\\s*:\\s*["\']' + protoMethod.replace(/[.*+?^${}()|[\\\\]\\]/g,'\\$&') + '["\'][\\s\\S]*?\\)', 'm');
        const mf = jsSrc.match(methodFinder);
        let methodName: string | null = null;
        if (mf && mf[1]) methodName = mf[1];
        if (!methodName) methodName = protoMethod.split('/').pop() || null;

        if (!methodName || methodName === 'constructor') continue;

        // Replace the method return signature in the d.ts with a robust multiline regex
        const methodNameEsc = methodName.replace(/[.*+?^${}()|[\\]/g, '\\$&');
        const sigRe = new RegExp('(' + methodNameEsc + '\\s*\\([^\\)]*\\)\\s*):[\\s\\S]*?;', 'g');
        dtsText = dtsText.replace(sigRe, function (fullMatch, p1) {
          changed = true;
          return p1 + ': Promise<' + typeName + '>';
        });
      }
      if (changed) {
        try {
          const genPath = path.join(outEsmDir, 'generated-types.d.ts');
          const rel = path.relative(path.dirname(dtsPath), genPath).replace(/\\/g, '/');
          const ref = '/// <reference path="' + rel + '" />\n';
          if (!dtsText.startsWith(ref)) dtsText = ref + dtsText;
        } catch (e) {}
        fs.writeFileSync(dtsPath, dtsText, 'utf8');
      }
    } catch (e) {}
  }

  // Also attempt a global pass over all .d.ts files under dist to catch any remaining inlined types
  try {
    const roots = [outEsmDir, outCjsDir];
    for (const root of roots) {
      if (!fs.existsSync(root)) continue;
      walkDir(root, (filePath) => {
        if (!filePath.endsWith('.d.ts')) return;
        if (/[/\\]examples([/\\]|$)/.test(filePath)) return;
        const jsPath = filePath.replace(/\.d\.ts$/, '.js');
        if (!fs.existsSync(jsPath)) return;
        try {
          const jsSrc = fs.readFileSync(jsPath, 'utf8');
          let dtsText = fs.readFileSync(filePath, 'utf8');
          let changed = false;
          const requestRe = /this\.request\(\s*\{([\s\S]*?)\}\s*,\s*([A-Za-z0-9_]+)\s*,/g;
          let m: RegExpExecArray | null;
          while ((m = requestRe.exec(jsSrc))) {
            const objText = m[1];
            const schemaName = m[2];
            const methodMatch = objText.match(/method\s*:\s*['\"]([^'\"]+)['\"]/);
            if (!methodMatch) continue;
            const protoMethod = methodMatch[1];
            const typeName = globalSchemaMap.get(schemaName);
            if (!typeName) continue;

            const methodFinder = new RegExp('(?:async\\s+)?([A-Za-z0-9_]+)\\s*\\([^\\)]*\\)\\s*\\{[\\s\\S]*?this\\.request\\(\\s*\\{[\\s\\S]*?method\\s*:\\s*["\']' + protoMethod.replace(/[.*+?^${}()|[\\\\]\\]/g,'\\$&') + '["\'][\\s\\S]*?\\)', 'm');
            const mf = jsSrc.match(methodFinder);
            let methodName: string | null = null;
            if (mf && mf[1]) methodName = mf[1];
            if (!methodName) methodName = protoMethod.split('/').pop() || null;

            if (methodName && methodName !== 'constructor') {
              // simple class body search-and-replace, best-effort
              const classRe = /export\s+declare\s+class[^{]+\{([\s\S]*?)\n\}/g;
              let cm: RegExpExecArray | null;
              let newDtsText = dtsText;
              while ((cm = classRe.exec(dtsText))) {
                const classBody = cm[1];
                const classStart = cm.index;
                const classEnd = classRe.lastIndex;
                const needle = methodName + '(';
                const localIdx = classBody.indexOf(needle);
                if (localIdx === -1) continue;
                const absOpen = classStart + 1 + localIdx + needle.length - 1;
                let depth = 0;
                let i = absOpen;
                let foundClose = -1;
                for (; i < classEnd; i++) {
                  const ch = dtsText[i];
                  if (ch === '(') depth++;
                  else if (ch === ')') {
                    depth--;
                    if (depth === 0) {
                      foundClose = i;
                      break;
                    }
                  }
                }
                if (foundClose === -1) continue;
                const semiIdx = dtsText.indexOf(';', foundClose);
                if (semiIdx === -1) continue;
                newDtsText = newDtsText.slice(0, foundClose + 1) + ': Promise<' + typeName + '>' + newDtsText.slice(semiIdx);
                changed = true;
              }
              if (changed) dtsText = newDtsText;
            }
          }
          if (changed) {
            try {
              const genPath = path.join(outEsmDir, 'generated-types.d.ts');
              const rel = path.relative(path.dirname(filePath), genPath).replace(/\\/g, '/');
              const ref = '/// <reference path="' + rel + '" />\n';
              if (!dtsText.startsWith(ref)) dtsText = ref + dtsText;
            } catch (e) {}
            fs.writeFileSync(filePath, dtsText, 'utf8');
          }
        } catch (e) {}
      });
    }
  } catch (e) {}

  console.log('generated per-module d.ts for', processed.length, 'modules');
}

if (process.argv[1].endsWith('generate-types.ts')) {
  main().catch((err) => {
    console.error('generate-types failed', err && (err as Error).stack || err);
    process.exit(1);
  });
}

// export helper for tests/consumers
// (astReplaceReturnTypes is already exported above via `export function ...`)
